[package]
name = "test-upnp-serve"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1.46.1", features = ["macros", "rt-multi-thread"] }
tracing-subscriber = "0.3.19"
librqbit-upnp-serve = { path = "../../crates/upnp-serve" }

[workspace]
