[package]
name = "test-peer-binary-protocol"
version = "0.1.0"
edition = "2024"

[dependencies]
librqbit-peer-protocol = { path = "../../crates/peer_binary_protocol", default-features = false }

[workspace]
