name: Debug 450 Build

on:
  push:
    branches:
      - debug-450

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          target: x86_64-pc-windows-msvc

      - name: Build test-random-core-deps
        run: cargo build --release
        working-directory: ./test-450/test-random-core-deps

      - name: Upload test-random-core-deps artifact
        uses: actions/upload-artifact@v4
        with:
          name: test-random-core-deps
          path: ./test-450/test-random-core-deps/target/release/test-random-core-deps.exe
