name: Release binaries for all platforms

on:
  push:
    branches: [docker]

env:
  CARGO_TERM_COLOR: always

jobs:
  cross-compile-on-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: install buildah
        run: brew tap slp/krun && brew install buildah

      - name: Login to Docker Hub
        run: buildah login --username '${{ secrets.DOCKERHUB_USERNAME }}' --password '${{ secrets.DOCKERHUB_PASSWORD }}' docker.io

      - name: try to build and push
        run: mkdir -p target/x86_64-unknown-linux-musl/release-github/ && touch target/x86_64-unknown-linux-musl/release-github/rqbit

      - name: hack Dockerfile user id
        run: cd docker && sed -i.bcp -e "s/501/$(id -u)/g" Dockerfile

      - name: debug
        run: id -u && id -g && cat docker/Dockerfile

      - name: build Docker image
        run: make buildah-x86_64

      - name: push Docker image
        run: buildah-x86_64-push
