name: Run tests

on:
  push:
    branches: [xx-docker]

jobs:
  build-push-docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ikatson/rqbit:test-${{ github.ref_name }}
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          file: docker/Dockerfile.xx
