name: Run tests

on:
  push:
    branches: [xx-docker]

jobs:
  build-push-docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        id: builder1

      - name: cross-compile all binaries
        run: mkdir -p target/cross && docker buildx ls &&
          docker build --builder ${{ steps.builder1.outputs.name }} --platform linux/amd64,linux/arm64,linux/arm/v7
          -f docker/Dockerfile.xx
          --cache-from=type=gha
          --cache-to=type=gha
          --output type=local,dest=target/cross .

      # linux_amd64/bin/rqbit -> linux/amd64/rqbit
      # linux_arm64/bin/rqbit -> linux/arm64/rqbit
      # linux_arm_v7/bin/rqbit -> linux/arm/v7/rqbit
      - name: Reorganize binaries in target/cross
        run:
          mkdir -p target/cross/linux/amd64/ target/cross/linux/arm64/ target/cross/linux/arm/v7 &&
          cd target/cross/ &&
          mv linux_amd64/bin/rqbit linux/amd64/ && chmod +x linux/amd64/rqbit &&
          mv linux_arm64/bin/rqbit linux/arm64/ && chmod +x linux/arm64/rqbit &&
          mv linux_arm_v7/bin/rqbit linux/arm/v7/ && chmod +x linux/arm/v7/rqbit

      # TODO: publish these as artifacts

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ikatson/rqbit:${{ github.ref_name }}
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          context: target/cross/
          file: docker/Dockerfile.xx
