name: Release binaries for all platforms

on:
  pull_request:
    branches: [docker]

env:
  CARGO_TERM_COLOR: always

jobs:
  cross-compile-on-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Make a directory for output artifacts
        run: mkdir -p target/artifacts

      - name: install linux cross compiler
        run: brew tap messense/macos-cross-toolchains &&
          brew install x86_64-unknown-linux-musl

      - name: Build release linux x86_64 binary
        run: rustup target install x86_64-unknown-linux-musl &&
          make release-linux-x86_64 &&
          mv target/x86_64-unknown-linux-musl/release-github/rqbit target/artifacts/rqbit-linux-static-x86_64

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: target/x86_64-unknown-linux-musl/release-github/
          file: docker/Dockerfile
          platforms: linux/amd64
          push: true
          tags: ikatson/rqbit:test
